name: Finance Data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"   # Run at 8:00 AM UTC (stock-titan)
    - cron: "0 20 * * *"  # Run at 8:00 PM UTC (yahoo-finance)
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v4.0.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run stock-titan
      working-directory: ./stock-titan
      env:
        DB_URL: ${{ secrets.DB_URL }}
      run: |
        export DB_URL=${{ secrets.DB_URL }} && make all
      

    - name: Run yahoo-finance
      working-directory: ./yahoo-finance
      env:
        DB_URL: ${{ secrets.DB_URL }}
      run: |
        export DB_URL=${{ env.DB_URL }} && make all

    - name: Commit and push changes
      run: |
        git config --global user.email "ayodejiyou@gmail.com"
        git config --global user.name "Ayodeji Yekeen"
        git add .
        git commit -m "Update files generated by scripts"
        git push
